# Generated by Django 2.0.3 on 2018-03-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField(null=True)),
                ('url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', 'New'), ('p', 'In process'), ('d', 'Done')], default='n', max_length=1)),
                ('total', models.PositiveSmallIntegerField(null=True)),
                ('processed', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Auction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grabber.Auction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grabber.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grabber.Site'),
        ),
        migrations.AddField(
            model_name='auction',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grabber.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='completion',
            unique_together={('auction', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('site', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together={('site', 'number')},
        ),
    ]
