# Generated by Django 2.0.3 on 2018-04-02 10:28

from django.db import migrations, models
import django.db.models.deletion
import grabber.models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('file', models.ImageField(storage=grabber.models.BigStorage(), upload_to='images')),
                ('position', models.PositiveSmallIntegerField()),
                ('size', models.CharField(choices=[('o', 'Original'), ('t', 'Thumbnail')], default='o', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Photo')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Raw')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'get_latest_by': 'number', 'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='completion',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='completion',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('p', 'In process'), ('d', 'Done'), ('f', 'Failed')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='raw',
            name='photos',
            field=models.ManyToManyField(through='grabber.PhotoRaw', to='grabber.Photo'),
        ),
    ]
